### PR TITLE
solve the enum serialization issue without mapping to entity

### PR DESCRIPTION
**Pull request by bnayae**
I suggest this solution to the enum serialization problem.
https://github.com/barnardos-au/Neo4jMapper/issues/17
This solution solve the problem with very little footprint.
And It can be improve it's own performance after tiny contribution to ServiceStack (https://github.com/ServiceStack/ServiceStack/pull/1215).
ServiceStack conribution will add the mapper to ToObjectDictionary which will avoid the second iteration on the dictionary.

### CODE REVIEW

**Comment by bnayae** [comment]
Service Stack already accept the other contribution.
https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack/AppUtils.cs
When they release new NuGet Version we can make it more efficient.

**Comment by neildobson-au** [comment]
Code looks good, but I'm a bit confused. So we now have an updated ServiceStack package available to us (which we're not currently using) and this has a modified extension method `ToObjectDictionary` which extends `IDataReader` which we're not using.

The PR you've submitted passes, but does not use the overloaded `ToObjectDictionary`.

So the main thing to sort out is, are you intending to offer some code which now uses IDataReader? Or convert objects to use this interface? Otherwise I'm not sure where the ServiceStack PR leaves us.

I'll await this before proceeding further with the PR.

Please don't take it the wrong way, I'm just not quite understanding your intentions here. I truly believe you're on the write track but I think you've picked the wrong extension method. The one we're using is in PlatformExtensions.cs in ServiceStack.Text. If your original PR targeted this method then I would agree with everything so far.

**Comment by bnayae** [comment]
You're right,
I was contributing the wrong ServiceStack repo.
I Will put new pull request on the ServiceStack.Text PlatformExtensions.cs ToObjectDictionary
but you mention "extends IDataReader" which I cannot see in ServiceStack.Text PlatformExtensions.cs

I'm looking on the following signature:
        public static Dictionary<string, object> ToObjectDictionary(this object obj)
please make sure that we're talking on the same method.

**Comment by neildobson-au** [comment]
No worries. What I was trying to explain was the *wrong* method (the one in your original PR to ServiceStack) extends `IDataReader`. The right one you have now identified.

However, another project I'm working on (and rather confusingly is a PR to the main ServiceStack framework) [#1213](https://github.com/ServiceStack/ServiceStack/pull/1213) uses a different mechanism to create dictionary maps. It uses `ConvertTo<>` in conjunction with some custom mapping. I think this method, or an alternative to it, might solve your problem without requiring a change to `ServiceStack.Text` framework.

See line 167 of Neo4jAuthRepository in https://github.com/ServiceStack/ServiceStack/pull/1213/files#diff-1516380e322328b2db9bce7fdccaa145

I need a day or two to look into it further.

**Comment by bnayae** [comment]
I will also need the equivalent to  WithEntities i.e. to convert collection of complex types.

How  will ConvertTo<Dictionary<string, object>>() will handle property of type enum?
Usually enum conversion require either a mapping delegate or convention, because enum can be convert to string or int.
if it convert to string there is the casing issue (Pascal / camel casing).

**Comment by bnayae** [comment]
Anyway I was posting this contribution to ServiceStack.Text 
https://github.com/ServiceStack/ServiceStack.Text/pull/525
You can check if it can help you.

**Comment by neildobson-au** [comment]
Replacing `ToObjectDictionary` with `ConvertTo` allows you to register custom mappers.

https://github.com/neildobson-au/Neo4jMapper/commit/d64c7330aa6dbe1ee40ff4f813e89ab244aad147

Advantage of this approach is there's no need to repeat your mapping logic for each call to `WithEntity` or `WithEntities`.

**Comment by bnayae** [comment]
Look like perfect solution, please let me know when it ready.

**Comment by neildobson-au** [comment]
Updated repo and packages
https://github.com/barnardos-au/Neo4jMapper/releases/tag/v1.0.9
https://www.nuget.org/packages/Neo4jMapper/1.0.9

Note the `Neo4j.Driver` package v4.0 has extensive API changes including splitting the async/sync operations into separate packages. We're now dependent on https://www.nuget.org/packages/Neo4j.Driver.Simple/ which includes both.

Outside of Neo4jMapper you may need some refactoring of session & transaction management code. See their docs for more info.

**Comment by neildobson-au** [comment]
@bnayae I saw the PR for ServiceStack.Text was accepted. There's usually a timeframe of ~2 months for new ServiceStack builds. Once this comes through we can look to overload the `WithEntity` and other methods so that custom mapping can be passed through as an alternative to the registered mappers. I'll keep an eye out for ServiceStack 5.9 which should include the changes and update accordingly.

**Pull request closed without merging**
